version: '3.8'

services:
  customs-service:
    build:
      context: ./CustomsService
    container_name: customs-service
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  inventory-service:
    build:
      context: ./InventoryService
    container_name: inventory-service
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  notification-service:
    build:
      context: ./NotificationService
    container_name: notification-service
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  orchestrator-service:
    build:
      context: ./OrchestratorService
    container_name: orchestrator-service
    ports:
      - "5004:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  order-service:
    build:
      context: ./OrderService
    container_name: order-service
    ports:
      - "5005:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  payment-service:
    build:
      context: ./PaymentService
    container_name: payment-service
    ports:
      - "5006:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  shipment-service:
    build:
      context: ./ShipmentService
    container_name: shipment-service
    ports:
      - "5007:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ broker
      - "15672:15672" # RabbitMQ management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest