version: '3.8'

services:
  customs-service:
    build:
      context: .
      dockerfile: ./CustomsService/Dockerfile
    container_name: customs-service
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  inventory-service:
    build:
      context: .
      dockerfile: ./InventoryService/Dockerfile
    container_name: inventory-service
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  notification-service:
    build:
      context: .
      dockerfile: ./NotificationService/Dockerfile
    container_name: notification-service
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  orchestrator-service:
    build:
      context: .
      dockerfile: ./OrchestratorService/Dockerfile
    container_name: orchestrator-service
    ports:
      - "5004:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  order-service:
    build:
      context: .
      dockerfile: ./OrderService/Dockerfile
    container_name: order-service
    ports:
      - "5005:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  payment-service:
    build:
      context: .
      dockerfile: ./PaymentService/Dockerfile
    container_name: payment-service
    ports:
      - "5006:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  shipment-service:
    build:
      context: .
      dockerfile: ./ShipmentService/Dockerfile
    container_name: shipment-service
    ports:
      - "5007:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development